//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClosureDate
    {
        public int AcademicYear { get; set; }
        public Nullable<System.DateTime> ClosureDate1 { get; set; }
        public Nullable<System.DateTime> FinalClosureDate { get; set; }
    }
}
